//Jocimar Borges Júnior, RA: 2565897
//Jocimar Borges Júnior, RA: 2565897
//Jocimar Borges Júnior, RA: 2565897

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jocim
 */
public class FormDadosUnicLap extends javax.swing.JFrame {

    /**
     * Creates new form FormDadosUnicLap
     */
    private BDLap tabelaBDLap = BDLap.geraBDLap();
    private static FormDadosUnicLap dadosLapUnic;

    public FormDadosUnicLap() {
        initComponents();
        setLocationRelativeTo(null);
        populaTabela();
    }
    //Sigleton Method
    public static FormDadosUnicLap geraDadosSmart(){
        if(dadosLapUnic == null){
            dadosLapUnic = new FormDadosUnicLap();
        }
        return dadosLapUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDadosLap = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbDadosLap.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tbDadosLap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Gerente", "Vendedor", "Estoque", "IMEI", "Modelo", "Fabricante", "Preço (R$)", "Tela (Polegadas)", "Memoria RAM", "Sistema Operacional", "Memória (GB)", "Processador", "Quantidade Estoque", "Quantidade Entradas", "Entrada de Fone"
            }
        ));
        jScrollPane1.setViewportView(tbDadosLap);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btVoltar))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose(); // Fecha a janela atual
    }//GEN-LAST:event_btVoltarActionPerformed
    public void limparTabela() {
    DefaultTableModel modelo = (DefaultTableModel) tbDadosLap.getModel();
    modelo.setRowCount(0);
}
    
    public void populaTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tbDadosLap.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Laptop l : tabelaBDLap.getBDLap()){
            if (l.getIMEI() == FormCadLap.getTextoPesquisaIMEI()) {
                modelo.addRow(new Object[]{
                    l.getGerente(),
                    l.getVendedor(),
                    l.verificarLocalizacao(),
                    l.getIMEI(),
                    l.getComp().getModelo(),
                    l.getComp().getFabricante(),
                    l.getPreco(),
                    l.getTelaPOlegadas(),
                    l.getMemoriaRAM(),
                    l.getSistemaOperacional(),
                    l.getArmazenamentoGB(),
                    l.getProcessador(),
                    l.verQtdEstoque(),
                    l.getQtdEntrada(),
                    l.getEntradaFone()
                });
                posLin++;
            }
        }
    }//fim do PopulaTabela
    
    public void sair(){
        int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        if(ret == 0){
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDadosLap;
    // End of variables declaration//GEN-END:variables
}

