//Versão do NetBeans: v22
//Jocimar Borges Júnior, RA: 2565897

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jocim
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotJanPrinc1 = new javax.swing.JLabel();
        rotJanPrinc2 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        barMenuPrincipal = new javax.swing.JMenuBar();
        mnIniciar = new javax.swing.JMenu();
        GerCelulares = new javax.swing.JMenu();
        CadConsAparelho = new javax.swing.JMenuItem();
        RelCelular = new javax.swing.JMenuItem();
        GerLaptops = new javax.swing.JMenu();
        CadConsAparelhoLap = new javax.swing.JMenuItem();
        RelLap = new javax.swing.JMenuItem();
        GerSmartWatchs = new javax.swing.JMenu();
        CadConsAparelhoLap1 = new javax.swing.JMenuItem();
        RelLap1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        rotJanPrinc1.setFont(new java.awt.Font("Roboto Light", 2, 24)); // NOI18N
        rotJanPrinc1.setText("Seja Bem-Vindo ao");

        rotJanPrinc2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rotJanPrinc2.setText("Sistema para Cadastro/Estoque de Eletrônicos");

        btSair.setText("SAIR");
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        mnIniciar.setText("Iniciar");

        GerCelulares.setText("Gerenciar Celulares");

        CadConsAparelho.setText("Cadastrar/Consultar um Aparelho");
        CadConsAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadConsAparelhoActionPerformed(evt);
            }
        });
        GerCelulares.add(CadConsAparelho);

        RelCelular.setText("Relatório Geral de Celulares");
        RelCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelCelularActionPerformed(evt);
            }
        });
        GerCelulares.add(RelCelular);

        mnIniciar.add(GerCelulares);

        GerLaptops.setText("Gerenciar Laptops");

        CadConsAparelhoLap.setText("Cadastrar/Consultar um Aparelho");
        CadConsAparelhoLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadConsAparelhoLapActionPerformed(evt);
            }
        });
        GerLaptops.add(CadConsAparelhoLap);

        RelLap.setText("Relatório Geral de Laptops");
        RelLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelLapActionPerformed(evt);
            }
        });
        GerLaptops.add(RelLap);

        mnIniciar.add(GerLaptops);

        GerSmartWatchs.setText("Gerenciar SmartWatchs");

        CadConsAparelhoLap1.setText("Cadastrar/Consultar um Aparelho");
        CadConsAparelhoLap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadConsAparelhoLap1ActionPerformed(evt);
            }
        });
        GerSmartWatchs.add(CadConsAparelhoLap1);

        RelLap1.setText("Relatório Geral de SmartWatchs");
        RelLap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelLap1ActionPerformed(evt);
            }
        });
        GerSmartWatchs.add(RelLap1);

        mnIniciar.add(GerSmartWatchs);

        barMenuPrincipal.add(mnIniciar);

        setJMenuBar(barMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rotJanPrinc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(rotJanPrinc1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(rotJanPrinc1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotJanPrinc2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadConsAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadConsAparelhoActionPerformed
        abraCadConsCel();
    }//GEN-LAST:event_CadConsAparelhoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void RelCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelCelularActionPerformed
        abraRelatGerCel();
    }//GEN-LAST:event_RelCelularActionPerformed

    private void CadConsAparelhoLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadConsAparelhoLapActionPerformed
        abraCadConsLap();
    }//GEN-LAST:event_CadConsAparelhoLapActionPerformed

    private void RelLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelLapActionPerformed
        abraRelatGerLap();
    }//GEN-LAST:event_RelLapActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void CadConsAparelhoLap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadConsAparelhoLap1ActionPerformed
        abraCadConsSmart();
    }//GEN-LAST:event_CadConsAparelhoLap1ActionPerformed

    private void RelLap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelLap1ActionPerformed
        abraRelatGerSmart();
    }//GEN-LAST:event_RelLap1ActionPerformed

    public void abraCadConsCel()
    {
        FormCadCel.geraCadCel().setVisible(true);
        
    }
    public void abraCadConsLap()
    {
        FormCadLap.geraCadLap().setVisible(true);
        
    }
    public void abraCadConsSmart()
    {
        FormCadSmart.geraCadSmart().setVisible(true);
        
    }
    public void sair(){
        int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        if(ret == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    
    public void abraRelatGerCel()
    {
        FormRelatGerCel.tbDadosCel().setVisible(true);
    }
    public void abraRelatGerLap()
    {
        FormRelatGerLap.tbDadosLap().setVisible(true);
    }
    public void abraRelatGerSmart()
    {
        FormRelatGerSmart.tbDadosSmart().setVisible(true);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadConsAparelho;
    private javax.swing.JMenuItem CadConsAparelhoLap;
    private javax.swing.JMenuItem CadConsAparelhoLap1;
    private javax.swing.JMenu GerCelulares;
    private javax.swing.JMenu GerLaptops;
    private javax.swing.JMenu GerSmartWatchs;
    private javax.swing.JMenuItem RelCelular;
    private javax.swing.JMenuItem RelLap;
    private javax.swing.JMenuItem RelLap1;
    private javax.swing.JMenuBar barMenuPrincipal;
    private javax.swing.JButton btSair;
    private javax.swing.JMenu mnIniciar;
    private javax.swing.JLabel rotJanPrinc1;
    private javax.swing.JLabel rotJanPrinc2;
    // End of variables declaration//GEN-END:variables
}
